# Introduction to PyTorch
## Tensors
### Check versions


In [1]:
import numpy as np
import torch
import sys
import matplotlib

# Check versions
print(f'Python version: {sys.version}')
print(f'Numpy version: {np.version.version}')
print(f'PyTorch version: {torch.version.__version__}')
print(f'Matplotlib version: {matplotlib.__version__}')
print(f'GPU present: {torch.cuda.is_available()}')

Python version: 3.8.6 (default, Dec  1 2020, 09:35:46) 
[GCC 10.2.0]
Numpy version: 1.19.4
PyTorch version: 1.9.0
Matplotlib version: 3.5.1
GPU present: True


### Tensors and their attributes

In [2]:
# Create simple tensor
a = torch.tensor([1,2,3,9])

# Some attributes
print('a: ', a)
print('Precision: ', a.dtype)
print('Device: ', a.device)
print('Shape: ', a.shape) # Returns tuple-like object of dimensions, also known as .size()
print('ndim: ', a.ndim)   # Number of dimensions, also known as .dim()
print('Requires grad: ', a.requires_grad)


a:  tensor([1, 2, 3, 9])
Precision:  torch.int64
Device:  cpu
Shape:  torch.Size([4])
ndim:  1
Requires grad:  False


### Changing location of a tensor

In [3]:
# Many ways to switch a tensors device.
a1 = a.to(torch.device('cuda'))
a2 = a.cpu()
a3 = a.cuda() # Shorthand


print('Device a: ', a.device)
print('Device a1: ', a1.device)
print('Device a2: ', a2.device)
print('Device a3: ', a3.device)

Device a:  cpu
Device a1:  cuda:0
Device a2:  cpu
Device a3:  cuda:0


### Changing precision

In [4]:
a = torch.arange(10)
print('a.dtype: ', a.dtype)
b = a.float()
c = a.double()
print('b.dtype: ', b.dtype)
print('c.dtype: ', c.dtype)

a.dtype:  torch.int64
b.dtype:  torch.float32
c.dtype:  torch.float64


### Reshaping a tensor

In [5]:
# Reshape a tensor
a = torch.tensor([1,2,3,9])
b = a.view(2,-1) # Same as `a.view(2,2)`


b[0,0] = 10
print(b)
print(a)
print ('-----------')

c = torch.reshape(a, (2,-1))

c[0,0] = -1
print(c)
print(a)
# All these tensors points to the same memory adress.

tensor([[10,  2],
        [ 3,  9]])
tensor([10,  2,  3,  9])
-----------
tensor([[-1,  2],
        [ 3,  9]])
tensor([-1,  2,  3,  9])


In [6]:
a = torch.arange(6)
b = a.view(3,2)
print('b: ', b)

c = b.transpose(0,1) # Swap axes 0 and 1
print('c: ', c)

b:  tensor([[0, 1],
        [2, 3],
        [4, 5]])
c:  tensor([[0, 2, 4],
        [1, 3, 5]])


### Numpy/torch functions

In [7]:
a = torch.eye(3, dtype=torch.double) # Identity matrix
b = torch.zeros([3,2,9]) # Tensor initialized to zero with the specified dimension
c = torch.ones([3,2,9])  # Tensor initialized to zero with the specified dimension
d = torch.rand((2,1,3))  # Tensor with random numbers in the interval [0,1)
e = torch.linspace(0,3,101) # 101 equistant points in the interval [0,3]

### Indexing
Uses the usual convetions from Numpy

In [8]:
a = torch.arange(10).view(2,-1)
print('a:\n', a)
print('\na[:, 1:3]:\n', a[:, 1:3])

a:
 tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

a[:, 1:3]:
 tensor([[1, 2],
        [6, 7]])


### Share data

In [9]:
x = np.linspace(0,1,101)
a = torch.from_numpy(x) # Convert numpy array to torch tensor
#print(a.dtype)

y = a.numpy() # Convert torch tensor to numpy array

z = x.copy()  # Copy the underlying memory
b = a.clone() # Copy the underlying memory

### Mathematical operations

In [10]:
x = torch.linspace(-1,1, 11)
print(x.abs())
print(x.max())
print(x.pow(2))
print(x.pow(2).sum().sqrt())

tensor([1.0000e+00, 8.0000e-01, 6.0000e-01, 4.0000e-01, 2.0000e-01, 1.4901e-08,
        2.0000e-01, 4.0000e-01, 6.0000e-01, 8.0000e-01, 1.0000e+00])
tensor(1.)
tensor([1.0000e+00, 6.4000e-01, 3.6000e-01, 1.6000e-01, 4.0000e-02, 2.2204e-16,
        4.0000e-02, 1.6000e-01, 3.6000e-01, 6.4000e-01, 1.0000e+00])
tensor(2.0976)
